- hosts: all
  become: true
  tasks:
   - name: install  all packages
     yum: 
      name: "{{item}}"
      state: present

     with_items:
       - httpd
       - git
       - vim
       - unzip
       - zip